require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProjectsTechnologiesController do
  before(:each) do
    Project.new(name: "Test")
    Technology.new(name: "C#")
  end

  # This should return the minimal set of attributes required to create a valid
  # ProjectsTechnology. As you add validations to ProjectsTechnology, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "project_id" => 1, "technology_id" => 1 } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProjectsTechnologiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all projects_technologies as @projects_technologies" do
      projects_technology = ProjectsTechnology.create! valid_attributes
      get :index, {}, valid_session
      assigns(:projects_technologies).should eq([projects_technology])
    end
  end

  describe "GET show" do
    it "assigns the requested projects_technology as @projects_technology" do
      projects_technology = ProjectsTechnology.create! valid_attributes
      get :show, {:id => projects_technology.to_param}, valid_session
      assigns(:projects_technology).should eq(projects_technology)
    end
  end

  describe "GET new" do
    it "assigns a new projects_technology as @projects_technology" do
      get :new, {}, valid_session
      assigns(:projects_technology).should be_a_new(ProjectsTechnology)
    end
  end

  describe "GET edit" do
    it "assigns the requested projects_technology as @projects_technology" do
      projects_technology = ProjectsTechnology.create! valid_attributes
      get :edit, {:id => projects_technology.to_param}, valid_session
      assigns(:projects_technology).should eq(projects_technology)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProjectsTechnology" do
        expect {
          post :create, {:projects_technology => valid_attributes}, valid_session
        }.to change(ProjectsTechnology, :count).by(1)
      end

      it "assigns a newly created projects_technology as @projects_technology" do
        post :create, {:projects_technology => valid_attributes}, valid_session
        assigns(:projects_technology).should be_a(ProjectsTechnology)
        assigns(:projects_technology).should be_persisted
      end

      it "redirects to the created projects_technology" do
        post :create, {:projects_technology => valid_attributes}, valid_session
        response.should redirect_to(ProjectsTechnology.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved projects_technology as @projects_technology" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectsTechnology.any_instance.stub(:save).and_return(false)
        post :create, {:projects_technology => { "project" => "invalid value" }}, valid_session
        assigns(:projects_technology).should be_a_new(ProjectsTechnology)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectsTechnology.any_instance.stub(:save).and_return(false)
        post :create, {:projects_technology => { "project" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested projects_technology" do
        projects_technology = ProjectsTechnology.create! valid_attributes
        # Assuming there are no other projects_technologies in the database, this
        # specifies that the ProjectsTechnology created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProjectsTechnology.any_instance.should_receive(:update).with({ "project_id" => "1" })
        put :update, {:id => projects_technology.to_param, :projects_technology => { "project_id" => "1" }}, valid_session
      end

      it "assigns the requested projects_technology as @projects_technology" do
        projects_technology = ProjectsTechnology.create! valid_attributes
        put :update, {:id => projects_technology.to_param, :projects_technology => valid_attributes}, valid_session
        assigns(:projects_technology).should eq(projects_technology)
      end

      it "redirects to the projects_technology" do
        projects_technology = ProjectsTechnology.create! valid_attributes
        put :update, {:id => projects_technology.to_param, :projects_technology => valid_attributes}, valid_session
        response.should redirect_to(projects_technology)
      end
    end

    describe "with invalid params" do
      it "assigns the projects_technology as @projects_technology" do
        projects_technology = ProjectsTechnology.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectsTechnology.any_instance.stub(:save).and_return(false)
        put :update, {:id => projects_technology.to_param, :projects_technology => { "project" => "invalid value" }}, valid_session
        assigns(:projects_technology).should eq(projects_technology)
      end

      it "re-renders the 'edit' template" do
        projects_technology = ProjectsTechnology.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectsTechnology.any_instance.stub(:save).and_return(false)
        put :update, {:id => projects_technology.to_param, :projects_technology => { "project" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested projects_technology" do
      projects_technology = ProjectsTechnology.create! valid_attributes
      expect {
        delete :destroy, {:id => projects_technology.to_param}, valid_session
      }.to change(ProjectsTechnology, :count).by(-1)
    end

    it "redirects to the projects_technologies list" do
      projects_technology = ProjectsTechnology.create! valid_attributes
      delete :destroy, {:id => projects_technology.to_param}, valid_session
      response.should redirect_to(projects_technologies_url)
    end
  end

end
